spring:
  application:
    name: user-service

server:
  port: 8056

com:
  lets:
    apis:
      client:
        generator:
          test-service-client: http://127.0.0.1:8055

feign:
  client:
    config:
      default:
        connectTimeout: 25000
        readTimeout: 25000
        loggerLevel: FULL