spring:
  application:
    name: test-service

server:
  port: 8055

com:
  lets:
    apis:
      client:
        generator:
          user-service-client: http://127.0.0.1:8056

feign:
  client:
    config:
      default:
        connectTimeout: 25000
        readTimeout: 25000
        loggerLevel: FULL